[versions]
agp = "9.3.1"
barcodeScanning = "17.3.0"
commonsCodec = "1.22.1"
camerax = "1.6.1"
core = "3.5.4"
gson = "2.14.0"
appcompat = "1.8.0"
kotlinOnetimepassword = "3.0.0"
material = "1.14.0"
firebaseCrashlyticsBuildtools = "3.0.8"
slidableactivity = "2.1.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }
core = { module = "com.google.zxing:core", version.ref = "core" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-onetimepassword = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "kotlinOnetimepassword" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
slidableactivity = { module = "com.r0adkll:slidableactivity", version.ref = "slidableactivity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

